### ISSUE TITLE
package does not work with Typescript

### ISSUE THREAD

**Issue by adahox** [takenet/blip-sdk-js#5]
After include blip-sdk-js i'm getting following error/warning:

`Could not find a declaration file for module 'blip-sdk'. 'c:/dev/apps/olharacessivel-com-br/node_modules/blip-sdk/dist/blip-sdk.js' implicitly has an 'any' type.
  Try npm install @types/blip-sdk if it exists or add a new declaration (.d.ts) file containing declare module 'blip-sdk';ts(7016)`

But @types/blip-sdk does not exist.

**Comment by andreminelli** [comment]
Hi, @adahox. 
This solution (install `@types/blip-sdk` is offered by NPM itself as a hint only.

We are using it on codebases using Typescript without problems. 
Can you provide us some code to reproduce this issue?

**Comment by adahox** [comment]
Hi @andreminelli . yes. sure.

follow my simple class that i'm importing blip-sdk:

`

     import * as BLiPSDK from "blip-sdk";
     import * as WebSocketTransport from "lime-transport-websocket";
     import * as Lime from "lime-js";


     export class BLiP {
    
         private identifier: string = 'sia2';
         private access_key: string = 'Y28wRERKRWtzS0NnVnZmY3JkMFo=';

         public bot: any; 
         constructor()
         {
              this.bot = new BLiPSDK.ClientBuilder()
             .withIdentifier(this.identifier)
             .withAccessKey(this.access_key)
             .withTransportFactory(() => new WebSocketTransport())
             .build();

             this.bot.connect();
         }
    }
`

That's the way i'm using the lib. if i change the way to import like:

`const blipsdk = require('blip-sdk');`

i getting error saying connect() function does not exists.

**Comment by adahox** [comment]
Hello @andreminelli,

Any way to fix that  ?

**Comment by jose-ramirez** [comment]
@adahox Have you tried to create the declaration file yourself? The message you're seeing has the hint at the end, to create a .d.ts file with `declare module 'blip-sdk';` in it so tyescript knows that what you're trying to import is a module

**Comment by adahox** [comment]
@jose-ramirez 

Worked perfectly.

I had not created index.d.ts because I believed it was mandatory to make all the correct exports to run. but just creating index.d.ts has already resolved and is now running.
I think the "problem" has been solved.

Thank you very much.

**Comment by jose-ramirez** [comment]
You're welcome!
